spring:
  data:
    mongodb:
      database: 
      uri: 

  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com


twilio:
  account:
    sid: 
  auth:
    token: 
  phone:
    number: 

server:
  port: 8080


logging:
  level:
    com.payment.wallet: DEBUG
    com.twilio: DEBUG
    org.springframework.security: DEBUG
